# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(default='', max_length=200)),
                ('author', models.CharField(blank=True, default='', max_length=200)),
                ('pub_date', models.DateTimeField()),
                ('text', models.TextField()),
                ('read_status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'commits',
            },
        ),
    ]
