# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha1', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=255)),
            ],
        ),
    ]
