# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commit',
            old_name='author',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='sha1',
        ),
        migrations.AddField(
            model_name='commit',
            name='email',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commit',
            name='sha',
            field=models.CharField(default='', max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
