# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170303_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
